try{

}catch(error){
    error
}
//ahora se puede sin pasar valor

try{

}catch{
    error
}